from decimal import Decimal
from django.core.management.base import BaseCommand
from django.utils.text import slugify
from shop.models import Category, Product


class Command(BaseCommand):
    help = "Seed ShopKart catalog — idempotent, safe to run multiple times."

    def handle(self, *args, **options):
        # ── ORIGINAL 50 PRODUCTS (unchanged) ─────────────────────────────────
        original_data = {
            'Electronics': [
                ('Wireless Headphones', 'Comfortable Bluetooth headphones with rich sound and soft ear cushions.', '2499.00', 25, 'products/wireless-headphones.svg'),
                ('Smart Watch', 'Modern smartwatch with fitness tracking and everyday notifications.', '3999.00', 15, 'products/smart-watch.svg'),
                ('Bluetooth Speaker', 'Portable wireless speaker with powerful audio and long battery life.', '1799.00', 20, 'products/bluetooth-speaker.svg'),
                ('Mechanical Keyboard', 'Compact mechanical keyboard for work, coding and gaming.', '3299.00', 18, 'products/mechanical-keyboard.svg'),
                ('Wireless Mouse', 'Ergonomic wireless mouse with smooth tracking and silent clicks.', '899.00', 35, 'products/wireless-mouse.svg'),
                ('USB-C Fast Charger', 'Compact fast charger for phones, tablets and compatible devices.', '1299.00', 40, 'products/usb-c-fast-charger.svg'),
                ('Power Bank 20000mAh', 'High-capacity power bank with dual USB outputs and USB-C input.', '1699.00', 28, 'products/power-bank-20000mah.svg'),
                ('Smartphone Stand', 'Adjustable desktop stand for comfortable video calls and viewing.', '499.00', 50, 'products/smartphone-stand.svg'),
                ('Webcam Full HD', 'Full HD webcam with clear video for classes, meetings and streaming.', '2199.00', 17, 'products/webcam-full-hd.svg'),
                ('LED Ring Light', 'Dimmable ring light for selfies, video calls and content creation.', '1499.00', 22, 'products/led-ring-light.svg'),
                ('Portable SSD 1TB', 'Fast portable solid-state drive for backups and large files.', '6999.00', 12, 'products/portable-ssd-1tb.svg'),
                ('Gaming Controller', 'Wireless controller with responsive buttons and dual-stick controls.', '2799.00', 14, 'products/gaming-controller.svg'),
                ('Smart LED Bulb', 'Color-changing smart bulb with adjustable brightness.', '699.00', 45, 'products/smart-led-bulb.svg'),
                ('Laptop Sleeve', 'Protective padded sleeve for everyday laptop carry.', '999.00', 30, 'products/laptop-sleeve.svg'),
                ('Mini Projector', 'Compact projector for movies, presentations and bedroom entertainment.', '5999.00', 10, 'products/mini-projector.svg'),
            ],
            'Fashion': [
                ('Classic Denim Jacket', 'A versatile denim jacket designed for everyday casual outfits.', '2199.00', 12, 'products/classic-denim-jacket.svg'),
                ('Running Shoes', 'Lightweight running shoes with comfortable everyday cushioning.', '2899.00', 18, 'products/running-shoes.svg'),
                ('Cotton T-Shirt', 'Soft cotton regular-fit t-shirt for a clean casual look.', '699.00', 40, 'products/cotton-t-shirt.svg'),
                ('Classic Sunglasses', 'Minimal everyday sunglasses with a timeless frame.', '999.00', 22, 'products/classic-sunglasses.svg'),
                ('Casual Sneakers', 'Everyday sneakers combining comfort with a clean streetwear look.', '2399.00', 20, 'products/casual-sneakers.svg'),
                ('Canvas Backpack', 'Spacious canvas backpack for college, office and short trips.', '1599.00', 25, 'products/canvas-backpack.svg'),
                ('Leather Wallet', 'Slim wallet with multiple card slots and a cash compartment.', '1199.00', 18, 'products/leather-wallet.svg'),
                ('Analog Wrist Watch', 'Classic analog wrist watch with a refined everyday dial.', '2499.00', 13, 'products/analog-wrist-watch.svg'),
                ('Hoodie', 'Soft fleece hoodie for relaxed and comfortable days.', '1799.00', 24, 'products/hoodie.svg'),
                ('Women Handbag', 'Elegant everyday handbag with practical storage space.', '2299.00', 16, 'products/women-handbag.svg'),
                ('Baseball Cap', 'Adjustable casual cap with a comfortable curved brim.', '599.00', 35, 'products/baseball-cap.svg'),
                ('Formal Shirt', 'Smart regular-fit formal shirt for office and occasions.', '1299.00', 27, 'products/formal-shirt.svg'),
            ],
            'Home': [
                ('LED Table Lamp', 'Modern adjustable LED lamp for study, work and bedside use.', '899.00', 30, 'products/led-table-lamp.svg'),
                ('Ceramic Coffee Mug', 'Minimal ceramic mug for your favourite tea or coffee.', '399.00', 50, 'products/ceramic-coffee-mug.svg'),
                ('Indoor Plant', 'Decorative indoor plant for a fresh home aesthetic.', '599.00', 24, 'products/indoor-plant.svg'),
                ('Cotton Cushion Set', 'Soft decorative cushion covers for a cozy living space.', '799.00', 30, 'products/cotton-cushion-set.svg'),
                ('Wall Clock', 'Minimal wall clock with a clean modern face.', '999.00', 20, 'products/wall-clock.svg'),
                ('Storage Basket', 'Woven storage basket for organizing everyday household items.', '699.00', 26, 'products/storage-basket.svg'),
                ('Bedsheet Set', 'Comfortable printed bedsheet set with matching pillow covers.', '1499.00', 18, 'products/bedsheet-set.svg'),
                ('Water Bottle', 'Reusable insulated bottle for home, office and travel.', '549.00', 45, 'products/water-bottle.svg'),
                ('Non-Stick Fry Pan', 'Durable non-stick pan for easy everyday cooking.', '1299.00', 19, 'products/non-stick-fry-pan.svg'),
                ('Table Organizer', 'Desk organizer for pens, notes and small accessories.', '499.00', 38, 'products/table-organizer.svg'),
                ('Scented Candle', 'Warm scented candle for a calm and cozy room atmosphere.', '449.00', 32, 'products/scented-candle.svg'),
                ('Kitchen Storage Jars', 'Clear storage jar set for neat pantry organization.', '899.00', 21, 'products/kitchen-storage-jars.svg'),
            ],
            'Beauty': [
                ('Floral Perfume', 'A fresh floral fragrance in an elegant compact bottle.', '1299.00', 16, 'products/floral-perfume.svg'),
                ('Face Moisturizer', 'Lightweight daily moisturizer for a smooth comfortable feel.', '699.00', 25, 'products/face-moisturizer.svg'),
                ('Lip Care Set', 'Simple lip-care duo for everyday hydration and softness.', '399.00', 35, 'products/lip-care-set.svg'),
                ('Makeup Brush Set', 'Soft-bristle brush set for easy everyday makeup application.', '999.00', 20, 'products/makeup-brush-set.svg'),
                ('Hair Dryer', 'Compact hair dryer with multiple heat and speed settings.', '1799.00', 15, 'products/hair-dryer.svg'),
                ('Body Mist', 'Fresh everyday body mist with a light pleasant fragrance.', '799.00', 22, 'products/body-mist.svg'),
            ],
            'Sports': [
                ('Yoga Mat', 'Non-slip cushioned yoga mat for stretching and home workouts.', '999.00', 28, 'products/yoga-mat.svg'),
                ('Skipping Rope', 'Lightweight skipping rope for cardio and fitness routines.', '299.00', 45, 'products/skipping-rope.svg'),
                ('Gym Water Bottle', 'Large reusable bottle designed for workouts and outdoor activity.', '599.00', 34, 'products/gym-water-bottle.svg'),
                ('Resistance Bands', 'Multi-level resistance bands for strength and mobility training.', '799.00', 30, 'products/resistance-bands.svg'),
                ('Football', 'Durable training football for recreational outdoor play.', '899.00', 18, 'products/football.svg'),
            ],
        }

        # ── 100 NEW PRODUCTS ─────────────────────────────────────────────────
        new_data = {
            'Smartphones': [
                ('iPhone Style Smartphone',
                 'Sleek flagship-style smartphone with OLED display, dual camera system and all-day battery life.',
                 '54999.00', 20, 'products/iphone-style-smartphone.svg'),
                ('Android Flagship Phone',
                 'Premium Android smartphone with a 108MP camera, 120Hz refresh rate and fast charging support.',
                 '44999.00', 25, 'products/android-flagship-phone.svg'),
                ('Budget Smartphone',
                 'Feature-packed budget phone with a large display, decent camera and reliable performance for daily use.',
                 '9999.00', 60, 'products/budget-smartphone.svg'),
                ('Foldable Smartphone',
                 'Innovative foldable phone that opens into a tablet-sized screen for productivity and media.',
                 '89999.00', 8, 'products/foldable-smartphone.svg'),
                ('Gaming Smartphone',
                 'High-refresh-rate gaming phone with dedicated cooling, shoulder triggers and an RGB accent strip.',
                 '39999.00', 14, 'products/gaming-smartphone.svg'),
                ('Rugged Smartphone',
                 'Military-grade rugged phone that is waterproof, dustproof and shockproof for outdoor adventures.',
                 '24999.00', 18, 'products/rugged-smartphone.svg'),
                ('5G Smartphone',
                 'Future-ready 5G phone with blazing-fast connectivity, capable processor and vibrant display.',
                 '29999.00', 30, 'products/5g-smartphone.svg'),
                ('Camera Phone',
                 'Photography-focused smartphone with a periscope zoom lens, large sensor and pro video modes.',
                 '49999.00', 16, 'products/camera-phone.svg'),
            ],
            'Laptops': [
                ('Ultrabook Laptop',
                 'Ultra-thin laptop weighing under 1.2 kg with a brilliant IPS display and all-day battery life.',
                 '74999.00', 12, 'products/ultrabook-laptop.svg'),
                ('Gaming Laptop',
                 'High-performance gaming laptop with dedicated GPU, 144Hz display and RGB keyboard backlight.',
                 '89999.00', 10, 'products/gaming-laptop.svg'),
                ('Business Laptop',
                 'Reliable business laptop with a comfortable keyboard, enterprise security features and fast SSD.',
                 '64999.00', 15, 'products/business-laptop.svg'),
                ('2-in-1 Laptop',
                 'Versatile convertible laptop that doubles as a tablet with a 360-degree hinge and touch display.',
                 '69999.00', 11, 'products/2-in-1-laptop.svg'),
                ('Chromebook',
                 'Lightweight Chromebook ideal for students with fast boot times, long battery and cloud integration.',
                 '29999.00', 20, 'products/chromebook.svg'),
                ('MacBook Style Laptop',
                 'Premium slim laptop with a stunning Retina-class display, silent keyboard and powerful processor.',
                 '109999.00', 8, 'products/macbook-style-laptop.svg'),
                ('Student Laptop',
                 'Affordable yet capable laptop built for students with solid performance and lightweight design.',
                 '39999.00', 22, 'products/student-laptop.svg'),
                ('Workstation Laptop',
                 'Professional workstation laptop with ECC memory support, colour-accurate display and dedicated GPU.',
                 '149999.00', 6, 'products/workstation-laptop.svg'),
            ],
            'Headphones': [
                ('Noise Cancelling Headphones',
                 'Industry-leading active noise cancellation headphones for focused work and immersive listening.',
                 '24999.00', 18, 'products/noise-cancelling-headphones.svg'),
                ('True Wireless Earbuds',
                 'Compact TWS earbuds with rich bass, touch controls, IPX5 water resistance and 30-hour total playtime.',
                 '7999.00', 35, 'products/true-wireless-earbuds.svg'),
                ('Sports Earphones',
                 'Secure-fit sports earphones with ear hooks, sweat resistance and energetic sound tuning.',
                 '3499.00', 30, 'products/sports-earphones.svg'),
                ('Studio Headphones',
                 'Flat-response studio monitor headphones for accurate mixing, mastering and critical listening.',
                 '14999.00', 12, 'products/studio-headphones.svg'),
                ('Gaming Headset',
                 '7.1 surround sound gaming headset with noise-cancelling mic for competitive online gaming.',
                 '5999.00', 20, 'products/gaming-headset.svg'),
                ('Open-Ear Headphones',
                 'Comfortable open-back headphones that let ambient sound in for natural, spacious audio staging.',
                 '19999.00', 9, 'products/open-ear-headphones.svg'),
                ('Kids Headphones',
                 'Volume-limited over-ear headphones designed for children with fun colours and durable build.',
                 '1999.00', 28, 'products/kids-headphones.svg'),
                ('Wireless Earphones',
                 'Neckband-free wireless earphones with magnetic buds, aptX support and 8-hour battery life.',
                 '4999.00', 25, 'products/wireless-earphones.svg'),
            ],
            'Watches': [
                ('Luxury Dress Watch',
                 'Elegant dress watch with a sapphire crystal glass, slim profile and a genuine leather strap.',
                 '12999.00', 10, 'products/luxury-dress-watch.svg'),
                ('Fitness Tracker',
                 'Slim fitness band tracking steps, heart rate, sleep quality and SpO2 with a 14-day battery.',
                 '3499.00', 40, 'products/fitness-tracker.svg'),
                ('Chronograph Watch',
                 'Sporty chronograph watch with three sub-dials, tachymeter bezel and stainless-steel case.',
                 '8999.00', 15, 'products/chronograph-watch.svg'),
                ('Smartwatch Pro',
                 'Advanced smartwatch with GPS, ECG, always-on display and over 100 workout modes.',
                 '22999.00', 18, 'products/smartwatch-pro.svg'),
                ('Dive Watch',
                 '200m water-resistant dive watch with a uni-directional bezel and luminous hands.',
                 '15999.00', 12, 'products/dive-watch.svg'),
                ('Ladies Watch',
                 'Elegant ladies watch with rose-gold tone case, Swarovski-crystal hour markers and mesh strap.',
                 '9999.00', 14, 'products/ladies-watch.svg'),
                ('Pocket Watch',
                 'Classic pocket watch with an engraved case, Roman numeral dial and a smooth chain.',
                 '4999.00', 8, 'products/pocket-watch.svg'),
            ],
            'Shoes': [
                ('Leather Oxford Shoes',
                 'Hand-stitched full-grain leather Oxford shoes for formal occasions and office wear.',
                 '5999.00', 16, 'products/leather-oxford-shoes.svg'),
                ('High Top Sneakers',
                 'Trendy high-top canvas sneakers with a vulcanized sole and padded ankle collar.',
                 '3499.00', 22, 'products/high-top-sneakers.svg'),
                ('Slip-On Shoes',
                 'Easy slip-on shoes with a memory foam insole and flexible outsole for all-day comfort.',
                 '2199.00', 30, 'products/slip-on-shoes.svg'),
                ('Hiking Boots',
                 'Waterproof mid-ankle hiking boots with aggressive grip outsole and ankle support.',
                 '6999.00', 14, 'products/hiking-boots.svg'),
                ('Loafers',
                 'Classic suede loafers with a penny keeper strap and leather lining for smart-casual looks.',
                 '4499.00', 18, 'products/loafers.svg'),
                ('Sandals',
                 'Comfortable EVA-sole sandals with adjustable hook-and-loop straps for summer wear.',
                 '1499.00', 35, 'products/sandals.svg'),
                ('Formal Dress Shoes',
                 'Polished cap-toe dress shoes in genuine leather, ideal for business and formal events.',
                 '7499.00', 12, 'products/formal-dress-shoes.svg'),
                ('Ankle Boots',
                 'Stylish ankle boots with a block heel, side zip and faux-suede upper for everyday wear.',
                 '5499.00', 16, 'products/ankle-boots.svg'),
            ],
            'Bags': [
                ('Leather Tote Bag',
                 'Spacious full-grain leather tote bag with internal zip pocket and sturdy double handles.',
                 '4999.00', 15, 'products/leather-tote-bag.svg'),
                ('Travel Duffel Bag',
                 'Large duffel bag with a wet pocket, padded shoulder strap and airline carry-on compatible size.',
                 '3499.00', 20, 'products/travel-duffel-bag.svg'),
                ('Crossbody Bag',
                 'Compact crossbody bag with an adjustable strap, RFID-blocking pocket and magnetic closure.',
                 '2799.00', 25, 'products/crossbody-bag.svg'),
                ('Laptop Backpack',
                 'Anti-theft laptop backpack with a USB charging port, hidden pockets and padded back panel.',
                 '3999.00', 20, 'products/laptop-backpack.svg'),
                ('Clutch Purse',
                 'Evening clutch purse with satin lining, wrist loop and magnetic snap for a polished look.',
                 '1999.00', 18, 'products/clutch-purse.svg'),
                ('Messenger Bag',
                 'Canvas messenger bag with quick-access flap, laptop sleeve and adjustable cross-body strap.',
                 '2499.00', 22, 'products/messenger-bag.svg'),
                ('Gym Bag',
                 'Durable gym bag with a ventilated shoe compartment, bottle holder and waterproof base.',
                 '1799.00', 28, 'products/gym-bag.svg'),
                ('Mini Backpack',
                 'Trendy mini backpack perfect for day trips and festivals with adjustable padded straps.',
                 '1599.00', 24, 'products/mini-backpack.svg'),
            ],
            'Home & Kitchen': [
                ('Electric Kettle',
                 '1.7-litre stainless steel electric kettle that boils water in under three minutes.',
                 '1299.00', 30, 'products/electric-kettle.svg'),
                ('Air Fryer',
                 '4-litre digital air fryer that cooks crispy food with up to 80% less oil.',
                 '4999.00', 18, 'products/air-fryer.svg'),
                ('Coffee Maker',
                 'Drip coffee maker with a programmable timer, keep-warm plate and a 12-cup glass carafe.',
                 '3499.00', 14, 'products/coffee-maker.svg'),
                ('Blender',
                 'High-speed countertop blender for smoothies, soups and sauces with a 1.5-litre jar.',
                 '2499.00', 16, 'products/blender.svg'),
                ('Toaster Oven',
                 'Compact toaster oven with convection fan, 6 cooking modes and a 25-litre capacity.',
                 '3999.00', 12, 'products/toaster-oven.svg'),
                ('Rice Cooker',
                 'Fuzzy-logic rice cooker with steaming tray, delay timer and keep-warm function.',
                 '2999.00', 20, 'products/rice-cooker.svg'),
                ('Food Processor',
                 'Multi-function food processor with chopping, slicing, grating and blending attachments.',
                 '4499.00', 10, 'products/food-processor.svg'),
                ('Electric Iron',
                 'Steam iron with a non-stick soleplate, self-cleaning function and burst-of-steam feature.',
                 '1499.00', 25, 'products/electric-iron.svg'),
                ('Vacuum Cleaner',
                 'Powerful cyclone vacuum cleaner with HEPA filter, 2200W motor and multiple attachments.',
                 '7999.00', 10, 'products/vacuum-cleaner.svg'),
                ('Ceiling Fan',
                 'Energy-efficient BLDC ceiling fan with remote control and a modern matte-finish blade set.',
                 '5499.00', 8, 'products/ceiling-fan.svg'),
                ('Curtains Set',
                 'Blackout curtain set with thermal insulation, machine-washable fabric and grommet top.',
                 '1999.00', 22, 'products/curtains.svg'),
                ('Photo Frame Set',
                 'Set of 3 wooden photo frames in classic walnut finish for wall display or table placement.',
                 '899.00', 35, 'products/photo-frame.svg'),
            ],
            'Beauty': [
                ('Sunscreen SPF 50',
                 'Broad-spectrum SPF 50 sunscreen with a lightweight gel texture that absorbs without grease.',
                 '699.00', 40, 'products/sunscreen-spf.svg'),
                ('Eye Cream',
                 'Caffeine-infused eye cream that reduces puffiness and dark circles with regular use.',
                 '1299.00', 22, 'products/eye-cream.svg'),
                ('Vitamin C Serum',
                 'Brightening Vitamin C serum with 20% ascorbic acid for a radiant and even complexion.',
                 '999.00', 28, 'products/vitamin-c-serum.svg'),
                ('Sheet Mask Pack',
                 'Pack of 10 hydrating sheet masks with hyaluronic acid for deep moisturisation.',
                 '599.00', 45, 'products/sheet-mask.svg'),
                ('Nail Polish Set',
                 'Long-lasting chip-resistant nail polish set with 12 trending shades and a strengthening base coat.',
                 '799.00', 30, 'products/nail-polish.svg'),
                ('Hair Serum',
                 'Frizz-control hair serum with argan oil that adds shine and protects from heat damage.',
                 '549.00', 35, 'products/hair-serum.svg'),
                ('Exfoliating Scrub',
                 'Gentle walnut-powder face scrub that unclogs pores, removes dead cells and leaves skin soft.',
                 '449.00', 38, 'products/exfoliating-scrub.svg'),
                ('Foaming Face Wash',
                 'Gentle foaming face wash with niacinamide and green tea extract for clear and bright skin.',
                 '349.00', 50, 'products/face-wash.svg'),
            ],
            'Sports': [
                ('Cricket Bat',
                 'English willow cricket bat with a mid-blade sweet spot and a high-performance toe guard.',
                 '3999.00', 14, 'products/cricket-bat.svg'),
                ('Basketball',
                 'Official size rubber basketball with deep channel design for better grip and dribble control.',
                 '1499.00', 22, 'products/basketball.svg'),
                ('Tennis Racket',
                 'Graphite tennis racket with a large sweet spot, vibration dampener and protective cover.',
                 '2999.00', 16, 'products/tennis-racket.svg'),
                ('Swimming Goggles',
                 'Anti-fog UV-protected swimming goggles with a silicone seal and adjustable split headband.',
                 '799.00', 30, 'products/swimming-goggles.svg'),
                ('Dumbbell Pair 5kg',
                 'Rubber-coated hex dumbbell pair in 5kg for home strength training and toning workouts.',
                 '1299.00', 25, 'products/dumbbell.svg'),
                ('Cycling Helmet',
                 'Aerodynamic cycling helmet with 18 ventilation channels, EPS liner and adjustable retention system.',
                 '2499.00', 18, 'products/cycling-helmet.svg'),
                ('Boxing Gloves',
                 'Genuine leather boxing gloves with triple-layer foam padding for training and sparring.',
                 '2199.00', 20, 'products/boxing-gloves.svg'),
                ('Jump Rope Pro',
                 'Speed jump rope with ball-bearing handles, adjustable steel cable and a digital counter.',
                 '999.00', 35, 'products/jump-rope-pro.svg'),
            ],
            'Accessories': [
                ('Reading Glasses',
                 'Lightweight anti-reflection reading glasses with spring hinges and a hard protective case.',
                 '599.00', 30, 'products/reading-glasses.svg'),
                ('Silk Scarf',
                 'Pure silk printed scarf with hand-rolled edges, versatile for neck, hair and bag styling.',
                 '1499.00', 20, 'products/silk-scarf.svg'),
                ('Leather Belt',
                 'Genuine leather dress belt with a brushed-silver pin buckle in classic black.',
                 '999.00', 25, 'products/leather-belt.svg'),
                ('Travel Pillow',
                 'Memory-foam U-shaped travel pillow with a breathable cover for long flights and road trips.',
                 '799.00', 32, 'products/travel-pillow.svg'),
                ('Aviator Sunglasses',
                 'Classic aviator sunglasses with UV400 polarised lenses and a stainless-steel double bridge.',
                 '1299.00', 22, 'products/sunglasses-aviator.svg'),
                ('Tie Clip',
                 'Stainless-steel tie bar with a polished gold finish for a sharp and well-groomed look.',
                 '499.00', 40, 'products/tie-clip.svg'),
                ('Cufflinks Set',
                 'Rhodium-plated cufflinks with inset enamel detail, presented in a luxury gift box.',
                 '1199.00', 18, 'products/cufflinks.svg'),
                ('Silicone Wristband',
                 'Motivational silicone wristband pack with engraved text in five colours.',
                 '299.00', 60, 'products/wrist-band.svg'),
                ('Phone Case',
                 'Drop-tested hybrid phone case with raised lips to protect the camera and display.',
                 '699.00', 45, 'products/phone-case.svg'),
                ('Card Holder',
                 'Slim aluminium card holder with a quick-release button that fans out up to 6 cards.',
                 '799.00', 35, 'products/card-holder.svg'),
                ('Keychain',
                 'Personalised multi-loop keychain with a carabiner clip and braided leather accent.',
                 '399.00', 50, 'products/keychain.svg'),
                ('Laptop Stand',
                 'Portable aluminium laptop stand with six adjustable height angles for ergonomic posture.',
                 '1599.00', 20, 'products/laptop-stand.svg'),
                ('Screen Protector',
                 'Tempered glass screen protector with oleophobic coating and 9H hardness rating.',
                 '299.00', 80, 'products/screen-protector.svg'),
                ('Wireless Charger Pad',
                 '15W fast wireless charging pad compatible with Qi-enabled phones, earbuds and smartwatches.',
                 '1299.00', 28, 'products/wireless-charger.svg'),
                ('Earphone Case',
                 'Hard-shell zippered case for earphones with a mesh pocket for cables and accessories.',
                 '499.00', 40, 'products/earphone-case.svg'),
            ],
        }

        # ── SEED FUNCTION (shared logic) ─────────────────────────────────────
        def seed_catalog(data):
            total = 0
            for category_name, products in data.items():
                category, _ = Category.objects.get_or_create(
                    name=category_name,
                    defaults={
                        "slug": slugify(category_name),
                        "description": f"Explore our {category_name.lower()} collection.",
                    },
                )
                # Update description in case it changed
                Category.objects.filter(pk=category.pk).update(
                    description=f"Explore our {category_name.lower()} collection."
                )
                for name, description, price, stock, image in products:
                    _, created = Product.objects.update_or_create(
                        slug=slugify(name),
                        defaults={
                            "category": category,
                            "name": name,
                            "description": description,
                            "price": Decimal(price),
                            "stock": stock,
                            "image": image,
                            "is_active": True,
                        },
                    )
                    total += 1
            return total

        original_count = seed_catalog(original_data)
        new_count = seed_catalog(new_data)

        total_products = Product.objects.filter(is_active=True).count()
        self.stdout.write(self.style.SUCCESS(
            f"Seeding complete.\n"
            f"  Original catalog entries processed : {original_count}\n"
            f"  New catalog entries processed      : {new_count}\n"
            f"  Total active products in database  : {total_products}"
        ))
